2025-06-16 15:48:37,128	INFO worker.py:1917 -- Started a local Ray instance.
[2m[36m(pid=2308665) [0m 0:   0%|          | 0.00/414 [00:00<?, ?it/s][2m[36m(pid=2308665) [0m 0: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 414/414 [00:00<00:00, 4.41Mit/s]                                                                   [2m[36m(pid=2308665) [0m 0: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 414/414 [00:00<00:00, 1.48Mit/s]
[Jun 16, 2025 03:48:51PM] No errors!
