2025-06-16 03:15:34,757	INFO worker.py:1917 -- Started a local Ray instance.
[2m[36m(pid=1289271) [0m 0:   0%|          | 0.00/2.00 [00:00<?, ?it/s]                                                             [2m[36m(pid=1289271) [0m 0:  50%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆ     | 1.00/2.00 [00:00<00:00, 547it/s][2m[36m(pid=1289271) [0m 0: 9.00it [00:01, 8.05it/s]                         [2m[36m(pid=1289271) [0m 0: 9.00it [00:01, 8.05it/s][2m[36m(pid=1289271) [0m 0: 14.0it [00:02, 4.36it/s][2m[36m(pid=1289271) [0m 0: 14.0it [00:02, 4.36it/s]                                          [2m[36m(pid=1289271) [0m 0: 14.0it [00:02, 4.78it/s]
[Jun 16, 2025 03:16:00AM] No errors!
